### Verbo GET – listar
GET http://localhost:8000/produto/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET id
GET http://localhost:8000/produto/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome": "python",
    "descricao": "python",
    "foto": "https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/community/logos/python-logo-only.png",
    "valor_unitario": 1.10
}

### Verbo PUT – atualiza 
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome": "c#",
    "descricao": "c#",
    "foto": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png",
    "valor_unitario": 2.10
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey