### Verbo GET – listar
GET http://localhost:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET id
GET http://localhost:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome" : "Soraia da Luz Vitoria", 
    "cpf" : "12345678909", 
    "telefone" : "49898989", 
    "compra_fiado" : 1234, 
    "dia_fiado" : 1, 
    "senha" : "bolinhas"
}

### Verbo PUT – atualiza 
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome" : "Soraia EDIT da Luz Vitoria", 
    "cpf" : "12345678909", 
    "telefone" : "49898989", 
    "compra_fiado" : 1234, 
    "dia_fiado" : 1, 
    "senha" : "bolinhas"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey